import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";

const nexa = localFont({
    src: [
        {
            path: "../../public/fonts/Nexa/Nexa-ExtraLight.ttf",
            weight: "200"
        },
        {
            path: "../../public/fonts/Nexa/Nexa-Heavy.ttf",
            weight: "900"
        },
    ],
    variable: "--font-nexa"
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${nexa.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
